---
- hosts: all
  become: true
  gather_facts: yes

  tasks:
     - name: Install apache
       yum: name=httpd state=latest

     - name: Restart apache & Enable apache
       service: name=httpd state=started
       service: name=httpd state=enabled

 #   - name: copy file
 #     copy: src=/source/index.html dest=/var/www/html
 #

