---
- hosts: all
  become: true
  gather_facts: yes
  
  tasks:
    - name: Install python3
      yum: name=python3 state=latest
      
    - name: Check python version
      shell: python3 --version

